### ISSUE TITLE
CLI Line-endings Causing Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by dowtkrob** [perliedman/query-overpass#37] opened 2019-05-13 10:51 UTC
Using `npm install query-overpass` on ubuntu 18.04 correctly installs query-overpass to `/usr/local/lib/node_modules/query-overpass`.

Running `query-overpass --version` results in the error `/usr/bin/env: 'node\r': No such file or directory`. The trailing `\r` being the result of windows line endings.

Converting `/usr/local/lib/node_modules/query-overpass/cli.js` to unix line endings using `dos2unix` fixes the issue, confirming the line endings are the issue.

**Comment by perliedman** [comment] 2019-09-07 09:17
Can't reproduce this on Ubuntu 19.04, so hopefully this was a temporary problem.

I'm closing this, but feel free to drop a comment if you think I should re-open.

**Closed by perliedman** 2019-09-07 09:17 UTC
